version: '3.8'

services:

  react_crud:
    container_name: react_crud
    image: xavierperez21/node:react_crud
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
